client:

  # default: 30
  # Timeout in seconds
  # WARNING: Developer Has disabled this for right now.
  vctimeout: 30

  # default: 2
  # idle websocket timeout in minutes
  idletimeout: 2

  # default: false
  # Only allow bedrock players to join the chat
  requireBedrock: false

  # default: true
  # Allows for the bedrock client to open a menu just by opening the emotes menu
  # WARNING: Make sure you have off-hand-emote turned off in geyser or there may
  #          be conflict
  useEmoteForSVG: true

server:

  group:

    # Settings for the default group for Svg players.
    default:

      # default: true
      # This decides whether the Svg group is created for players who use the website
      enabled: true

      # default: 1a2b
      # This control's the default groups's password.
      password: 1a2b

  # default: 8080
  # port server will run on.
  port: 8080

  # default: 0.0.0.0
  # Address server binds to, use 127.0.0.1 to only connect from host device.
  # This is suggested to be changed only if you are running a proxy on the same network/device as the server to allow https/wss.
  bind-address: 0.0.0.0

# default: false
# Debug logs
# Do NOT use this in production. This will very quickly fill up your server logs.
debug: false
