const langData = {
    "en": {
        "brandName": "SimpleVoice-Geyser",
        "joinLabel": "Join Simple Voice Chat",
        "loginSubtitle": "Sign in with your Minecraft username and SVG password.",
        "usernameInput": "Minecraft username",
        "passwordInput": "SVG password",
        "showPassword": "Show",
        "hidePassword": "Hide",
        "firstTimeTitle": "First time connecting?",
        "pswdHelp": "Join the Minecraft server and run:",
        "pswdHelpDetail": "Your password must be 8–32 characters. Return here and sign in using your Minecraft username and the password you created.",
        "msAccountWarn": "Your SVG password is not your Microsoft, Mojang, or Minecraft account password. Never enter your Microsoft account password here.",
        "bedrockHint": "Bedrock players can sign in with their gamertag; SVG resolves the Floodgate prefix when the match is unique.",
        "micSelect": "Microphone",
        "speakSelect": "Speaker",
        "micLoad": "Loading microphones…",
        "speakLoad": "Loading speakers…",
        "joinBtnText": "Log In",
        "joinWait": "Waiting to join…",
        "msgText": "Message",
        "sendBtnText": "Send",
        "transmitModeLabel": "Transmit Mode",
        "micSLabel": "Microphone",
        "muteBtnText": "Mute",
        "voiceActivityText": "Voice Activation",
        "pushToTalkText": "Push-To-Talk",
        "pttBindingLabel": "PTT Binding",
        "bindPttBtnText": "Bind Push-to-Talk",
        "clearPttBtnText": "Clear Binding",
        "pttBindingDescription": "No binding set. Use the hold button or add a binding.",
        "allowBackgroundPttText": "Allow background controller PTT",
        "pttLabel": "Push-to-Talk",
        "pushToTalkBtnText": "Hold to Talk",
        "fullscreenPttBtnText": "Fullscreen PTT",
        "debugAudioLabel": "Debug Audio",
        "testSoundBtnText": "Test Sound",
        "colorEditorLabel": "Color Customization",
        "pushToTalkFullscreenBtnText": "Hold to Talk",
        "exitFullscreenPttBtnText": "Exit Fullscreen",
        "devToolsLabel": "Developer Tools",
        "dashboardTitle": "Voice Panel",
        "playerLabel": "Player",
        "wsStatusLabel": "Connection",
        "audioModeLabel": "Audio mode",
        "currentGroupLabel": "Current group",
        "logoutBtn": "Log Out",
        "groupsHeading": "Voice Groups",
        "createGroupBtn": "Create Group",
        "leaveGroupBtn": "Leave Group",
        "groupTypeHint": "NORMAL: proximity + group · OPEN: hear nearby outsiders · ISOLATED: group only",
        "nativeVoiceNotice": "Voice is currently handled by your in-game Simple Voice Chat client.",
        "voiceControlsHeading": "Voice Controls",
        "chatHeading": "Chat",
        "createGroupTitle": "Create Group",
        "groupNameLabel": "Group name",
        "groupPasswordOptional": "Group password",
        "groupTypeLabel": "Group type",
        "cancelBtn": "Cancel",
        "createGroupConfirm": "Create Group",
        "joinGroupTitle": "Join Protected Group",
        "groupPasswordLabel": "Password",
        "joinGroupConfirm": "Join"
    },
    "pl": {
        "brandName": "SimpleVoice-Geyser",
        "joinLabel": "Dołącz do Simple Voice Chat",
        "loginSubtitle": "Zaloguj się nazwą Minecraft i hasłem SVG.",
        "usernameInput": "Nazwa użytkownika Minecraft",
        "passwordInput": "Hasło SVG",
        "showPassword": "Pokaż",
        "hidePassword": "Ukryj",
        "firstTimeTitle": "Pierwsze połączenie?",
        "pswdHelp": "Dołącz do serwera Minecraft i wpisz:",
        "pswdHelpDetail": "Hasło musi mieć 8–32 znaki. Wróć tutaj i zaloguj się nazwą Minecraft oraz utworzonym hasłem.",
        "msAccountWarn": "Hasło SVG to nie hasło konta Microsoft, Mojang ani Minecraft. Nigdy nie wpisuj tutaj hasła Microsoft.",
        "bedrockHint": "Bedrock: możesz użyć gamertagu; SVG dopasuje prefiks Floodgate, gdy wynik jest jednoznaczny.",
        "micSelect": "Mikrofon",
        "speakSelect": "Głośnik",
        "micLoad": "Ładowanie mikrofonów…",
        "speakLoad": "Ładowanie głośników…",
        "joinBtnText": "Zaloguj",
        "joinWait": "Oczekiwanie na połączenie…",
        "msgText": "Wiadomość",
        "sendBtnText": "Wyślij",
        "transmitModeLabel": "Tryb nadawania",
        "micSLabel": "Mikrofon",
        "muteBtnText": "Wycisz",
        "voiceActivityText": "Aktywacja głosem",
        "pushToTalkText": "Naciśnij i mów (PTT)",
        "pttBindingLabel": "Przypisanie klawisza PTT",
        "bindPttBtnText": "Przypisz klawisz Push-to-Talk",
        "clearPttBtnText": "Usuń przypisanie klawisza",
        "pttBindingDescription": "Brak przypisanego klawisza. Użyj przycisku ekranowego lub przypisz klawisz.",
        "allowBackgroundPttText": "Zezwól na PTT na kontrolerze w tle",
        "pttLabel": "Naciśnij i mów",
        "pushToTalkBtnText": "Przytrzymaj, aby mówić",
        "fullscreenPttBtnText": "Tryb pełnoekranowy PTT",
        "debugAudioLabel": "Diagnostyka dźwięku",
        "testSoundBtnText": "Test dźwięku",
        "colorEditorLabel": "Personalizacja kolorów",
        "pushToTalkFullscreenBtnText": "Przytrzymaj, aby mówić",
        "exitFullscreenPttBtnText": "Zamknij pełny ekran",
        "devToolsLabel": "Narzędzia deweloperskie",
        "dashboardTitle": "Panel głosowy",
        "playerLabel": "Gracz",
        "wsStatusLabel": "Połączenie",
        "audioModeLabel": "Tryb audio",
        "currentGroupLabel": "Aktualna grupa",
        "logoutBtn": "Wyloguj",
        "groupsHeading": "Grupy głosowe",
        "createGroupBtn": "Utwórz grupę",
        "leaveGroupBtn": "Opuść grupę",
        "groupTypeHint": "NORMAL: bliskość + grupa · OPEN: słyszysz pobliskich · ISOLATED: tylko grupa",
        "nativeVoiceNotice": "Głos obsługuje klient Simple Voice Chat w grze.",
        "voiceControlsHeading": "Sterowanie głosem",
        "chatHeading": "Czat",
        "createGroupTitle": "Utwórz grupę",
        "groupNameLabel": "Nazwa",
        "groupPasswordOptional": "Hasło (opcjonalne)",
        "groupTypeLabel": "Typ",
        "cancelBtn": "Anuluj",
        "createGroupConfirm": "Utwórz",
        "joinGroupTitle": "Dołącz do chronionej grupy",
        "groupPasswordLabel": "Hasło",
        "joinGroupConfirm": "Dołącz"
    },
    "it": {
        "brandName": "SimpleVoice-Geyser",
        "joinLabel": "Unisciti a Simple Voice Chat",
        "loginSubtitle": "Accedi con il nome Minecraft e la password SVG.",
        "usernameInput": "Nome utente Minecraft",
        "passwordInput": "Password SVG",
        "showPassword": "Mostra",
        "hidePassword": "Nascondi",
        "firstTimeTitle": "Prima connessione?",
        "pswdHelp": "Entra nel server Minecraft ed esegui:",
        "pswdHelpDetail": "La password deve avere 8–32 caratteri. Torna qui e accedi con il nome Minecraft e la password creata.",
        "msAccountWarn": "La password SVG non è la password dell'account Microsoft, Mojang o Minecraft. Non inserire mai qui la password Microsoft.",
        "bedrockHint": "Bedrock: puoi usare il gamertag; SVG risolve il prefisso Floodgate quando la corrispondenza è univoca.",
        "micSelect": "Microfono",
        "speakSelect": "Altoparlante",
        "micLoad": "Caricamento microfoni…",
        "speakLoad": "Caricamento altoparlanti…",
        "joinBtnText": "Accedi",
        "joinWait": "In attesa di connessione…",
        "msgText": "Messaggio",
        "sendBtnText": "Invia",
        "transmitModeLabel": "Modalità di trasmissione",
        "micSLabel": "Microfono",
        "muteBtnText": "Silenzia",
        "voiceActivityText": "Attivazione vocale",
        "pushToTalkText": "Premere per parlare (PTT)",
        "pttBindingLabel": "Assegnazione tasto PTT",
        "bindPttBtnText": "Assegna tasto Push-to-Talk",
        "clearPttBtnText": "Rimuovi assegnazione tasto",
        "pttBindingDescription": "Nessun tasto assegnato. Usa il pulsante a schermo o assegna un tasto.",
        "allowBackgroundPttText": "Consenti PTT tramite controller in background",
        "pttLabel": "Premere per parlare",
        "pushToTalkBtnText": "Tieni premuto per parlare",
        "fullscreenPttBtnText": "PTT a schermo intero",
        "debugAudioLabel": "Diagnostica audio",
        "testSoundBtnText": "Test audio",
        "colorEditorLabel": "Personalizzazione colori",
        "pushToTalkFullscreenBtnText": "Tieni premuto per parlare",
        "exitFullscreenPttBtnText": "Esci da schermo intero",
        "devToolsLabel": "Strumenti per sviluppatori",
        "dashboardTitle": "Pannello vocale",
        "playerLabel": "Giocatore",
        "wsStatusLabel": "Connessione",
        "audioModeLabel": "Modalità audio",
        "currentGroupLabel": "Gruppo attuale",
        "logoutBtn": "Esci",
        "groupsHeading": "Gruppi vocali",
        "createGroupBtn": "Crea gruppo",
        "leaveGroupBtn": "Lascia gruppo",
        "groupTypeHint": "NORMAL: prossimità + gruppo · OPEN: senti i vicini · ISOLATED: solo gruppo",
        "nativeVoiceNotice": "La voce è gestita dal client Simple Voice Chat in gioco.",
        "voiceControlsHeading": "Controlli vocali",
        "chatHeading": "Chat",
        "createGroupTitle": "Crea gruppo",
        "groupNameLabel": "Nome",
        "groupPasswordOptional": "Password (opzionale)",
        "groupTypeLabel": "Tipo",
        "cancelBtn": "Annulla",
        "createGroupConfirm": "Crea",
        "joinGroupTitle": "Unisciti al gruppo protetto",
        "groupPasswordLabel": "Password",
        "joinGroupConfirm": "Unisciti"
    }
};

document.addEventListener("DOMContentLoaded", () => {
    let userLang = navigator.language || navigator.userLanguage || "en";
    userLang = userLang.slice(0, 2);

    if (!(userLang in langData)) {
        userLang = "en";
    }

    const language = langData[userLang];

    document.querySelectorAll("[svg-lang]").forEach((element) => {
        const key = element.getAttribute("svg-lang");

        if (key in language) {
            element.textContent = language[key];
        }
    });
});
