voicechat:
  server_host: "localhost"
  server_port: 25566

webserver:
  port: 8080

proximity:
  default_radius: 50.0
  forced: true

permissions:
  nonprox: "simplevoicegeyser.nonprox" # Permission to create non-proximity channels
